title: Stux Society.
description: The Internet is a serious business. 
baseurl: ""
url: "https://themayankjha.github.io" 

author-name:   Lex
author-avatar: lex.jpg

github: https://github.com/themayankjha
instafeed: false 
google-analytics: 

markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

exclude: [excludes,README.md,LICENSE.md,CNAME]